### ISSUE TITLE
Appointment Form

### ISSUE THREAD

**Issue by raghavsoni114** [bawejahritik/AutoServ#10]
Create appointment booking form for input parameters

**Comment by bawejahritik** [comment]
Car details

- Car number
- Name
- Phone number
- Email
- (Authorization)*

Choose service type**

- Date and time
- Self
- Pickup and drop

**Comment by amisinghal** [comment]
We should add the owners street address as well in the form.

**Comment by bawejahritik** [comment]
How about we only ask that from the users who choose for a car pickup service?

**Comment by raghavsoni114** [comment]
Yes, form should ask for address if "pick up and drop" is chosen by user.
