### ISSUE TITLE
HomePage: LeftDisplay : Image Size

### ISSUE THREAD

**Issue by bawejahritik** [bawejahritik/AutoServ#31]
Should we decrease the size of the image and see how it appears?

**Comment by raghavsoni114** [comment]
Sure. Working on it.

**Comment by raghavsoni114** [comment]
![image](https://user-images.githubusercontent.com/42437530/150869058-a0be17b0-8e70-452c-8c4c-128868f71f7f.png)

Is this layout better?

**Comment by bawejahritik** [comment]
yess this looks good
