### ISSUE TITLE
HomePage: Display Placement  

### ISSUE THREAD

**Issue by bawejahritik** [bawejahritik/AutoServ#47]
Should we switch the display to the opposite side and see how it looks?

**Comment by raghavsoni114** [comment]
Interchanging the position of carousel and display?

**Comment by bawejahritik** [comment]
Yes. Just wondering which might be visually appealing.

**Comment by raghavsoni114** [comment]
![image](https://user-images.githubusercontent.com/42437530/152440509-4258b023-a43b-4777-b423-43ba0da124e4.png)
Display, buttons on right

![image](https://user-images.githubusercontent.com/42437530/152440663-16eac42a-847a-486a-af26-e6871ab13870.png)
Display, buttons on left

**Comment by bawejahritik** [comment]
The buttons on the left one looks better.

**Comment by raghavsoni114** [comment]
Ok. The Homepage UI design should also be updated accordingly.
