### ISSUE TITLE
Null values in Database from frontend

### ISSUE THREAD

**Issue by bawejahritik** [bawejahritik/AutoServ#92]
![image](https://user-images.githubusercontent.com/53797247/154717255-6579aaa1-08fa-4885-9e7f-cff6657f4ea5.png)

**Comment by raghavsoni114** [comment]
Server is getting NULL values for both 'Content-Type' : 'application/x-www-form-urlencoded' and 'Content-Type' : 'application/json'

**Comment by raghavsoni114** [comment]
![image](https://user-images.githubusercontent.com/42437530/154828583-55fc8246-8ff1-44bb-ba73-baeb8c7bda0b.png)
forms.service.ts is getting correct values but subscribe function in appointment-form.component.ts shows null
